name: Docs

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

env:
  CI: true
  NODE: 12.x
  RUBY: 2.6.x

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "${{ env.NODE }}"

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ env.RUBY }}

      - name: Disable gem docs
        run: 'echo "gem: --no-document" > ~/.gemrc'

      - name: Get npm cache directory
        id: npm-cache
        run: |
          echo "::set-output name=dir::$(npm config get cache)"

      - name: Set up npm cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.dir }}
          key: ${{ runner.os }}-node-v${{ env.node }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}}
          restore-keys: |
            ${{ runner.OS }}-node-v${{ env.node }}-${{ hashFiles('package.json') }}-${{ hashFiles('package-lock.json') }}
            ${{ runner.OS }}-node-v${{ env.node }}-

      - name: Set up Ruby cache
        uses: actions/cache@v2
        with:
          path: docs/vendor/bundle
          key: ${{ runner.os }}-ruby-v${{ env.RUBY }}-${{ hashFiles('docs/Gemfile') }}-${{ hashFiles('docs/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-ruby-v${{ env.RUBY }}-${{ hashFiles('docs/Gemfile') }}-${{ hashFiles('docs/Gemfile.lock') }}
            ${{ runner.os }}-ruby-v${{ env.RUBY }}-

      - name: Set up Bundler
        run: gem install bundler -v "~> 1.17"

      - run: ruby --version
      - run: gem --version
      - run: bundle --version
      - run: java -version

      - name: Install npm dependencies
        run: npm ci

      - name: Install bundler dependencies
        run: bundle install --gemfile docs/Gemfile --deployment --jobs=4 --retry=3 --clean

      - name: Build docs
        run: npm run docs-compile

      - name: Run HTML validator
        run: npm run docs-lint
